/                         : "Home"
/about-us                 : "About Us"
/community/?             : "Community"
/do-more                  : "Do More"
/faq                      : "FAQ"
/feedback                 : "Feedback"
/how-it-works             : "How It Works"
/match-savers/?           : "Match Savers"
/pledges/savetogether_ask : "Donate to SaveTogether"
/privacy-policy           : "Privacy Policy"
/signup-or-login          : "Sign up or Log In"
/terms-of-use             : "Terms of Use"

/donors/[0-9]+            : "Donor Profile"
/organizations/[0-9]+     : "Organization Profile"
/pledges/[_a-z]+to_pledge : "Pledge"
/savers/[0-9]+            : "Saver Profile"
