/               : "Home"
/about-us       : "About Us"
/community/     : "Community"
/do-more        : "Do More"
/faq            : "FAQ"
/feedback       : "Feedback"
/how-it-works   : "How It Works"
/match-savers/  : "Match Savers"
/privacy-policy : "Privacy Policy"
/terms-of-use   : "Terms of Use"

/donors/[0-9]+  : "Donor Profile"
/savers/[0-9]+  : "Saver Profile"
